steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', '-t', 'gcr.io/$PROJECT_ID/k8s-node-termination-handler', '-f', 'Dockerfile.build', '.' 
  ]
images:
- 'gcr.io/$PROJECT_ID/k8s-node-termination-handler'
